### ISSUE TITLE
Missing arm-linux-androideabi-gcc

### ISSUE THREAD

**Issue by kvark** [rust-windowing/android-rs-glue#208]
Following the readme instructions and reaching the point of running it:
```
cargo apk build
Compiling android_native_app_glue.c
error: could not execute process `/hub/tools/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc /hub/tools/android-ndk-r19c/sources/android/native_app_glue/android_native_app_glue.c -c -o /hub/moz/wr/target/android-artifacts/armv7-linux-androideabi/android_native_app_glue.o --sysroot /hub/tools/android-ndk-r19c/platforms/android-28/arch-arm` (never executed)

Caused by:
  No such file or directory (os error 2)
```
Checking the binaries in this folder:
```
kvark@ant /hub/tools/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin $ ls
arm-linux-androideabi-addr2line  arm-linux-androideabi-c++filt  arm-linux-androideabi-gprof   arm-linux-androideabi-ld.gold  arm-linux-androideabi-objdump  arm-linux-androideabi-size
arm-linux-androideabi-ar         arm-linux-androideabi-dwp      arm-linux-androideabi-ld      arm-linux-androideabi-nm       arm-linux-androideabi-ranlib   arm-linux-androideabi-strings
arm-linux-androideabi-as         arm-linux-androideabi-elfedit  arm-linux-androideabi-ld.bfd  arm-linux-androideabi-objcopy  arm-linux-androideabi-readelf  arm-linux-androideabi-strip
```

**Comment by digiwizkid** [comment]
I am also getting similar issues with NDK version 19.2.*

<pre>cargo apk build          
<font color="#8AE234">Compiling android_native_app_glue.c</font>
<font color="#EF2929"><b>error:</b></font> could not execute process `/home/subhadipl/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc <br/> /home/subhadipl/Android/Sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.c -c -o <br/> /home/subhadipl/rusts/helloAndroid/target/android-artifacts/arm-linux-androideabi/android_native_app_glue.o --sysroot <br/> /home/subhadipl/Android/Sdk/ndk-bundle/platforms/android-18/arch-arm` (never executed)

Caused by:
  No such file or directory (os error 2)
</pre>

**Comment by kvark** [comment]
I tried "r18b" NDK and now getting a different error:
> /hub/tools/android-ndk-r18b/sources/android/native_app_glue/android_native_app_glue.c:18:10: fatal error: 'jni.h' file not found

**Comment by shreevari** [comment]
What does -c do in this command?

**Comment by digiwizkid** [comment]
-c                      Only run preprocess, compile, and assemble steps

**Comment by Gordon-F** [comment]
Looks like GCC not a part of the NDK.

https://github.com/android-ndk/ndk/issues/802

**Comment by shijunti19** [comment]
How to solve it?

**Comment by krystcich** [comment]
@shijunti19 you need to download a revision before r18b e.g. 
https://developer.android.com/ndk/downloads/older_releases.html#ndk-17c-downloads

That made `Compiling android_native_app_glue.c` error to go away for me.

**Comment by mb64** [comment]
Fixed by #223.

**Comment by i-schuetz** [comment]
@mb64 Could you please explain how to use master ("manual usage")? If I do what's in the readme now it still shows the same error.

**Comment by philip-alldredge** [comment]
The version on crates.io is an older version unfortunately. See #221. To work around, either use the docker or checkout the code from git and install using `cargo install --locked --force --path .` from the `cargo-apk` directory.
